<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aiderminal</name>
  <version>0.1.0</version>
  <description>Aider 遥操作机器人共享 Python 库</description>
  <maintainer email="miuseik@tencent.com">miuseik</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
