<?xml version="1.0"?>
<package format="3">
  <name>robot_localization</name>
  <version>0.1.0</version>
  <description>定位 (滤波融合, robot_localization)</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>robot_localization</depend>
</package>
