<?xml version="1.0"?>
<package format="3">
  <name>robot_sensors</name>
  <version>0.1.0</version>
  <description>传感器驱动 (采集并发布 sensor_msgs)</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>robot_msgs</depend>
</package>
