<?xml version="1.0"?>
<package format="3">
  <name>robot_tests</name>
  <version>0.1.0</version>
  <description>测试 (unittest/launch_testing)</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_lint_auto</test_depend>
</package>
