<?xml version="1.0"?>
<package format="3">
  <name>robot_interaction</name>
  <version>0.1.0</version>
  <description>交互 (HMI/语音/WS桥)</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>robot_msgs</depend>
</package>
